package orm;

/**
 * TLiuyan generated by MyEclipse Persistence Tools
 */

public class TLiuyan implements java.io.Serializable
{

	private String id;
	private String yisheng_id;
	private String neirong;
	private String liuyanshi;
	
	private String user_id;
	private String huifu;
	private String huifushi;
	
	private Tuser user;
	private Tyisheng yisheng;

	public String getHuifu()
	{
		return huifu;
	}

	public void setHuifu(String huifu)
	{
		this.huifu = huifu;
	}

	public String getHuifushi()
	{
		return huifushi;
	}

	public void setHuifushi(String huifushi)
	{
		this.huifushi = huifushi;
	}

	
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getYisheng_id() {
		return yisheng_id;
	}

	public void setYisheng_id(String yisheng_id) {
		this.yisheng_id = yisheng_id;
	}

	public Tyisheng getYisheng() {
		return yisheng;
	}

	public void setYisheng(Tyisheng yisheng) {
		this.yisheng = yisheng;
	}

	public String getLiuyanshi()
	{
		return liuyanshi;
	}

	public void setLiuyanshi(String liuyanshi)
	{
		this.liuyanshi = liuyanshi;
	}

	public String getNeirong()
	{
		return neirong;
	}

	public void setNeirong(String neirong)
	{
		this.neirong = neirong;
	}

	public Tuser getUser()
	{
		return user;
	}

	public void setUser(Tuser user)
	{
		this.user = user;
	}

	public String getUser_id()
	{
		return user_id;
	}

	public void setUser_id(String user_id)
	{
		this.user_id = user_id;
	}

	
}